// Parsed flower data from flowerlist.md
export const flowers = [
  // ID List #2 - Priority 1
  { scientific: "Alpinia", common: ["ginger", "torch ginger"], listPriority: 1 },
  { scientific: "Anthurium", common: ["tail flower", "flamingo flower"], listPriority: 1 },
  { scientific: "Heliconia", common: ["lobster claw"], listPriority: 1 },
  { scientific: "Leucospermum", common: ["pincushion protea"], listPriority: 1 },
  { scientific: "Protea", common: ["protea"], listPriority: 1 },
  { scientific: "Strelitzia reginae", common: ["bird of paradise"], listPriority: 1 },
  { scientific: "Helleborus", common: ["hellebore", "Lenten rose", "Christmas rose"], listPriority: 1 },
  { scientific: "Banksia", common: ["banksia", "banksia protea", "bird's nest banksia"], listPriority: 1 },
  { scientific: "Leucadendron", common: ["flame tip", "conebush"], listPriority: 1 },
  { scientific: "Freesia", common: ["freesia"], listPriority: 1 },
  { scientific: "Agapanthus africanus", common: ["lily of the Nile", "African lily"], listPriority: 1 },
  { scientific: "Oncidium", common: ["oncidium orchid", "golden shower", "dancing lady"], listPriority: 1 },
  { scientific: "Scabiosa", common: ["pincushion flower", "scabiosus"], listPriority: 1 },
  { scientific: "Astrantia", common: ["masterwort"], listPriority: 1 },
  { scientific: "Phalaenopsis", common: ["phalaenopsis orchid", "moth orchid"], listPriority: 1 },
  { scientific: "Ammi", common: ["Queen Anne's lace", "lace flower"], listPriority: 1 },
  { scientific: "Lathyrus", common: ["sweetpea"], listPriority: 1 },
  { scientific: "Cymbidium", common: ["cymbidium orchid"], listPriority: 1 },
  { scientific: "Astilbe", common: ["false spiraea", "goat's beard"], listPriority: 1 },
  { scientific: "Papaver", common: ["poppy"], listPriority: 1 },
  { scientific: "Dendrobium", common: ["dendrobium orchid"], listPriority: 1 },
  { scientific: "Amaranthus", common: ["tassel flower"], listPriority: 1 },
  { scientific: "Craspedia globosa", common: ["billy button", "billy ball", "drumstick", "Australian bachelor button"], listPriority: 1 },
  { scientific: "Eryngium", common: ["sea holly"], listPriority: 1 },
  { scientific: "Tagetes", common: ["marigold"], listPriority: 1 },
  { scientific: "Digitalis", common: ["foxglove"], listPriority: 1 },
  { scientific: "Tweedia", common: ["tweedia", "blue star"], listPriority: 1 },
  { scientific: "Zantedeschia", common: ["calla", "calla lily", "arum lily"], listPriority: 1 },
  { scientific: "Tanacetum", common: ["feverfew", "pyrethrum", "tansy"], listPriority: 1 },
  { scientific: "Xerochrysum", common: ["strawflower", "everlasting flower", "golden everlasting"], listPriority: 1 },
  { scientific: "Narcissus", common: ["daffodil"], listPriority: 1 },
  { scientific: "Iris", common: ["Dutch iris", "flags"], listPriority: 1 },
  { scientific: "Talinum paniculatum", common: ["fame flower", "jewels of opar", "pink baby's breath"], listPriority: 1 },

  // ID List #1 - Priority 2
  { scientific: "Rosa (spray)", common: ["spray rose"], listPriority: 2 },
  { scientific: "Gypsophila paniculata", common: ["baby's breath"], listPriority: 2 },
  { scientific: "Solidago canadensis", common: ["goldenrod", "yellow aster"], listPriority: 2 },
  { scientific: "Gomphrena", common: ["globe amaranth"], listPriority: 2 },
  { scientific: "Chamelaucium uncinatum", common: ["waxflower"], listPriority: 2 },
  { scientific: "Limonium", common: ["statice"], listPriority: 2 },
  { scientific: "Chrysanthemum (button)", common: ["button mum"], listPriority: 2 },
  { scientific: "Chrysanthemum (daisy)", common: ["daisy mum", "spray daisy"], listPriority: 2 },
  { scientific: "Chrysanthemum (cushion)", common: ["cushion-mum"], listPriority: 2 },
  { scientific: "Celosia argentea", common: ["celosia", "cockscomb", "brain flower", "wool flower"], listPriority: 2 },
  { scientific: "Antirrhinum majus", common: ["snapdragon"], listPriority: 2 },
  { scientific: "Consolida ajacis", common: ["larkspur"], listPriority: 2 },
  { scientific: "Delphinium", common: ["delphinium"], listPriority: 2 },
  { scientific: "Gladiolus", common: ["sword lily", "gladiolus"], listPriority: 2 },
  { scientific: "Liatris spicata", common: ["blazing star", "purple poker", "gayfeather", "button snakeroot"], listPriority: 2 },
  { scientific: "Moluccella laevis", common: ["bells of Ireland", "shell flower"], listPriority: 2 },
  { scientific: "Rosa (standard)", common: ["rose (standard)"], listPriority: 2 },
  { scientific: "Rosa (garden)", common: ["garden rose", "cabbage rose"], listPriority: 2 },
  { scientific: "Anemone coronaria", common: ["windflower", "anemone"], listPriority: 2 },
  { scientific: "Dahlia", common: ["dahlia"], listPriority: 2 },
  { scientific: "Eustoma grandiflorum", common: ["lisianthus"], listPriority: 2 },
  { scientific: "Gerbera", common: ["African daisy", "gerbera daisy", "gerber daisy"], listPriority: 2 },
  { scientific: "Chrysanthemum (standard)", common: ["standard mum", "disbud mum"], listPriority: 2 },
  { scientific: "Zinnia elegans", common: ["zinnia", "youth-and-old-age"], listPriority: 2 },
  { scientific: "Hydrangea macrophylla", common: ["hydrangea"], listPriority: 2 },
  { scientific: "Paeonia", common: ["peony"], listPriority: 2 },
  { scientific: "Matthiola incana", common: ["stock"], listPriority: 2 },
  { scientific: "Cosmos bipinnatus", common: ["cosmo"], listPriority: 2 },
  { scientific: "Tulipa", common: ["tulip"], listPriority: 2 },
  { scientific: "Dianthus caryophyllus", common: ["carnation"], listPriority: 2 },
  { scientific: "Lilium", common: ["lily"], listPriority: 2 },
  { scientific: "Ranunculus asiaticus", common: ["Persian buttercup"], listPriority: 2 },
  { scientific: "Alstroemeria", common: ["Peruvian lily", "lily of the Incas", "Inca lily", "alstroemeria", "alstro"], listPriority: 2 },
  { scientific: "Helianthus annuus", common: ["sunflower"], listPriority: 2 },
  { scientific: "Hypericum", common: ["hypericum berry"], listPriority: 2 },
  { scientific: "Sedum", common: ["stonecrop"], listPriority: 2 },

  // Foliage & Ornamentals - Priority 3
  { scientific: "Philodendron bipinnatifidum", common: ["hope philodendron", "tree philodendron"], listPriority: 3 },
  { scientific: "Equisetum", common: ["snake grass", "horsetail"], listPriority: 3 },
  { scientific: "Monstera deliciosa", common: ["Swiss cheese plant", "split-leaf philodendron"], listPriority: 3 },
  { scientific: "Brassica oleracea", common: ["ornamental kale", "ornamental cabbage"], listPriority: 3 },
  { scientific: "Myrtus communis", common: ["myrtle"], listPriority: 3 },
  { scientific: "Liriope muscari", common: ["lily turf", "variegated lily turf"], listPriority: 3 },
  { scientific: "Gaultheria shallon", common: ["lemon leaf", "salal"], listPriority: 3 },
  { scientific: "Rumohra adiantiformis", common: ["leather leaf fern"], listPriority: 3 },
  { scientific: "Pittosporum", common: ["pittosporum", "pitt", "variegated pitt", "variegated pittosporum"], listPriority: 3 },
  { scientific: "Eucalyptus (seeded)", common: ["seeded eucalyptus"], listPriority: 3 },
  { scientific: "Eucalyptus (spiral)", common: ["spiral eucalyptus", "baby blue eucalyptus"], listPriority: 3 },
  { scientific: "Xerophyllum tenax", common: ["bear grass"], listPriority: 3 },
  { scientific: "Eucalyptus (silver dollar)", common: ["silver dollar eucalyptus"], listPriority: 3 },
  { scientific: "Eucalyptus (gunnii)", common: ["gunnii eucalyptus"], listPriority: 3 },
  { scientific: "Salix babylonica", common: ["curly willow", "corkscrew willow"], listPriority: 3 }
];
